#version 460


layout(constant_id = 0) const uint WORK_GROUP_SIZE = 1024;

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer Vals {
	uint vals[];
};

layout(set = 0, binding = 1, std430) readonly buffer WgPrefixSums {
	uint wg_prefix_sums[];
};

void main() {
	if (gl_GlobalInvocationID.x >= vals.length()) return;
	vals[gl_GlobalInvocationID.x] += wg_prefix_sums[gl_WorkGroupID.x];
}
